### PR TITLE
add alt text to 3 web build pages

### LINKED ISSUE #64: Add alt-text tags to web build pages
Add alt-text tags to the web build pages (there are 3 of them). 

In the code at: _posts/build_web/
Pages on the web are:
https://wildaid.github.io/web/2020/06/09/Prepare-Web-App.html
https://wildaid.github.io/web/2020/06/09/Build-Web-App.html
https://wildaid.github.io/web/2020/06/09/Test-Web-App.html

A brief guide to alt-text tags can be found in our style guide at https://wildaid.github.io/style/2020/10/02/Alt-Text.html

### PR DESCRIPTION
**Pull request by aayushi2883**
## Related Issue

Fixes #64

## Checklist:

- [x] I have read the [contributor's guide](https://wildaid.github.io/contribute/index.html).
- [ ] I linked an issue in the previous section
- [ ] I have commented on the linked issue
- [x] I was assigned the linked issue (not required)
- [x] I have tested the change to the best of my ability against the [sandbox](https://wildaid.github.io/contribute/sandbox.html) or a [local build](https://wildaid.github.io/build).
- [x] All my images have [appropriate alt tags](https://wildaid.github.io/style/2020/10/02/Alt-Text.html)

Optional items:

- [ ] My change adds new text and requires a change to translations.
- [ ] I was not able to test... (explain below, e.g. you did not have permissions to test a specific feature)
- [ ] This change depends O-FISH Realm repository changes (explain below)
- [ ] This change depends O-FISH Web repository changes (explain below)

* **Optional: Add any explanations here** 

* **Optional: Add any relevant screenshots here**

### CODE REVIEW

**Review by Sheeri — CHANGES_REQUESTED** [review]
Hello - in many cases these alt tags are not providing any information. Imagine looking at the page as it appears here - you can't actually see the image. What do you need to know, that might be seen in the image? If there's truly nothing, you can use alt="", but in most cases, there is some information you can put into it.

If you need some inspiration, check out https://wildaid.github.io/style/2020/10/02/Alt-Text.html and the 2 links at the bottom of that page for more examples.

**Comment by aayushi2883** [comment]
Okay, I'll solve it

**Comment by aayushi2883** [comment]
I have done a few changes, could you give a review on that please @Sheeri

**Review by Sheeri — APPROVED** [review]

**Comment by Sheeri** [comment]
Congratulations! 🎉 🙌 🎆 ㊗️ 

This PR is great and has been merged into the code. Thanks so much for contributing! If you'd like, you can request to work on another issue. We really appreciate your effort!

**Comment by Sheeri** [comment]
Hi @aayushi2883! 
We noticed you haven't gotten your MongoDB digital swag. To claim your O-FISH badge, head on over to the [MongoDB Community forums](https://developer.mongodb.com/community/forums/t/open-source-contributors-pick-up-your-badges-here/10167/9), login, and reply - making sure to link to this PR.

**Pull request merged**
