### PR TITLE
Adding alt-text tags to fix issue #69

### LINKED ISSUE #69: Add alt-text tags to Embed Boarding List Chart page
Add alt-text tags to the Embed Boarding List Chart page. 

Page exists at: https://wildaid.github.io/charts/2020/06/12/Embed-Boardings-List.html
In the code at: _posts/build_charts/2020-06-12-Embed-Boardings-List.md

A brief guide to alt-text tags can be found in our style guide at https://wildaid.github.io/style/2020/10/02/Alt-Text.html

### PR DESCRIPTION
**Pull request by GabbyJ**
## Related Issue

Fix #69

## Checklist:

- [x ] I have read the [contributor's guide](https://wildaid.github.io/contribute/index.html).
- [x ] I linked an issue in the previous section
- [x ] I have commented on the linked issue
- [x ] I was assigned the linked issue (not required)
- [x ] I have tested the change to the best of my ability against the [sandbox](https://wildaid.github.io/contribute/sandbox.html) or a [local build](https://wildaid.github.io/build).
- [x ] All my images have [appropriate alt tags](https://wildaid.github.io/style/2020/10/02/Alt-Text.html)

Optional items:

- [ ] My change adds new text and requires a change to translations.
- [ ] I was not able to test... (explain below, e.g. you did not have permissions to test a specific feature)
- [ ] This change depends O-FISH Realm repository changes (explain below)
- [ ] This change depends O-FISH Web repository changes (explain below)

* **Optional: Add any explanations here** 

* **Optional: Add any relevant screenshots here**

### CODE REVIEW

**Review by Sheeri — APPROVED** [review]
These are really fantastic alt tags - well done!

**Comment by Sheeri** [comment]
Congratulations! 🎉 🙌 🎆 ㊗️ 

This PR is great and has been merged into the code. Thanks so much for contributing! If you'd like, you can request to work on another issue. We really appreciate your effort!

**Comment by Sheeri** [comment]
Hi @GabbyJ! 
We noticed you haven't gotten your MongoDB digital swag. To claim your O-FISH badge, head on over to the [MongoDB Community forums](https://developer.mongodb.com/community/forums/t/open-source-contributors-pick-up-your-badges-here/10167/9), login, and reply - making sure to link to this PR.

**Comment by GabbyJ** [comment]
I didn't even know I had MongoDB digital swag to claim. Just did it! Thanks @Sheeri for allowing me to contribute to open source!

**Comment by Sheeri** [comment]
Woo hoo! We didn't want you to miss out, @GabbyJ!!!

**Pull request merged**
